stages:
  - deploy
  - report

variables:
  SITE_NAME: $CI_PROJECT_NAME

deploy:
  stage: deploy
  tags:
    - windows-iis
  only:
    - Develop
    - cicd
  script:
    - powershell -ExecutionPolicy Bypass -File .\deploy.ps1 -SiteName "$env:SITE_NAME"

report-log:
  stage: report
  tags:
    - windows-iis
  variables:
    GIT_STRATEGY: none
  only:
    - Develop
    - cicd
  script:
    - pm2 logs "$env:SITE_NAME" --nostream --lines 200
