stages:
  - pre-stop
  - build
  - deploy
  - report

variables:
  SITE_NAME: $CI_PROJECT_NAME

stop-app:
  stage: pre-stop
  tags:
    - windows-iis
  variables:
    GIT_STRATEGY: none
  only:
    - Develop
    - cicd
  script:
    - powershell.exe -Command "pm2 delete $env:SITE_NAME 2>`$null; exit 0"

build-app:
  stage: build
  tags:
    - windows-iis
  only:
    - Develop
    - cicd
  script:
    - echo $PWD

deploy:
  stage: deploy
  tags:
    - windows-iis
  variables:
    GIT_STRATEGY: none
  only:
    - Develop
    - cicd
  script:
    - xcopy /Y /E /I C:\Users\Public\node_modules node_modules
    - xcopy /Y /E /I C:\Users\Public\forprisma node_modules
    # - npm install --registry="https://mirror-npm.runflare.com"
    - npm install --registry="https://mirror-npm.runflare.com"
    # - npx prisma migrate reset -f
    # - npx prisma migrate dev --name reset data
    - npx prisma generate
    # - npx tsx scripts/seed-chat.ts
    # - npx tsx scripts/seed-timer.ts
    # - npx tsx scripts/seed-rooms.ts
    # - npx tsx scripts/seed-levels.ts
    # - npx tsx scripts/seed-inventory.ts
    # - npx tsx scripts/seed-starter-packs.ts
    - Write-Host "Starting deployment script..."
    - powershell -ExecutionPolicy Bypass -File .\deploy.ps1 -SiteName "$env:SITE_NAME"
  environment:
    name: production/$CI_PROJECT_NAME

report-log:
  stage: report
  tags:
    - windows-iis
  variables:
    GIT_STRATEGY: none
  only:
    - Develop
    - cicd
  script:
    - pm2 logs "$env:SITE_NAME" --nostream --lines 200
